spring.application.name=demo

# ============================================
# CONFIGURACIÓN DE BASE DE DATOS PostgreSQL
# ============================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / Hibernate
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Evita warnings con el nuevo dialecto de Hibernate (Spring Boot 4)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Puerto del servidor Spring Boot
server.port=8080
